title: 3aransia
email: 3aransia@3aransia.com
description: >- # this means to ignore newlines until "baseurl:"
    3aransia is a Moroccan Latin/Digit Language Framework that processes latin digit morroccan and arabian words and make them understandable and consumable by nowadays technologies 
baseurl: "" # the subpath of your site, e.g. /blog
url: "3aransia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 3aransia
github_username:  3aransia

# Build settings
theme: minima
plugins:
  - jekyll-feed